# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18c5f3caab835689120af9f1e49eea110019be6b0f0be410fe4173aa2a8e4d944cf5038b314168380d45695b4a18438099c0accbbdb2169801f9b7dc86054479

test:
  secret_key_base: ef2aac4e9cbf58e6d2a6bddcac03f998d252653bef07c6a19b783073e44ece08369b39a94c4a28b6c14e0866579cf023e68b42750b94f44e30e178f0ea9ff2f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
